name: DataPlatformDevOps
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read 
jobs:
  devops-automation:
    runs-on: ["aws-hosted-runner"]
    steps:
      - name: Checkout local repo
        uses: actions/checkout@v4
      - name: Configure AWS access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEV_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          disable-retry: "true"
      - name: Get STS Caller Identity
        run: aws sts get-caller-identity
      - name: List S3 Buckets
        run: aws s3 ls
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.AWS_DEV_ACCOUNT_ID }}
      - name: Configure EKS Cluster
        env:
          KUBECONFIG: ~/.kube/config
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status.
          aws eks update-kubeconfig --name ${{ secrets.AWS_DEV_EKS_CLUSTER }} --kubeconfig $KUBECONFIG
          kubectl config use-context ${{ secrets.AWS_DEV_EKS_CLUSTER }} --kubeconfig $KUBECONFIG
          kubectl config view --kubeconfig $KUBECONFIG
          kubectl config current-context --kubeconfig $KUBECONFIG
          kubectl cluster-info --kubeconfig $KUBECONFIG
      
      
